import React from 'react'
import MegaMenu from 'src/components/main-navigation/mega-menu/MegaMenu'

export default {
  title: 'PRESIDIO/Mega Menu',
  component: MegaMenu,
}

const Template = (args) => <MegaMenu {...args} />

export const Standard = Template.bind({})
Standard.args = {
  menuData: {
    menuItems: {
      2: {
        menuid: 279,
        url: '#',
        title: 'Transit & Directions',
        post_id: 'transit-directions',
        menu_item_parent: '276',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 0,
        menuitem: {
          3: {
            menuid: 280,
            url: '#',
            title: 'Getting to & Around  the Park',
            post_id: 'getting-to-around-the-park',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 1,
          },
          4: {
            menuid: 281,
            url: '#',
            title: 'Presidio Go Shuttle',
            post_id: 'presidio-go-shuttle',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 2,
          },
          5: {
            menuid: 282,
            url: '#',
            title: 'Parking',
            post_id: 'parking',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 3,
          },
          6: {
            menuid: 283,
            url: '#',
            title: 'Bike Rentals',
            post_id: 'bike-rentals',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 4,
          },
          7: {
            menuid: 284,
            url: '#',
            title: 'Maps',
            post_id: 'maps',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 5,
          },
        },
      },
      8: {
        menuid: 285,
        url: '#',
        title: 'Visitor Services',
        post_id: 'visitor-services',
        menu_item_parent: '276',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 6,
        menuitem: {
          9: {
            menuid: 286,
            url: '#',
            title: 'Visitor Center',
            post_id: 'visitor-center',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 7,
          },
          10: {
            menuid: 290,
            url: '#',
            title: 'Contact Us',
            post_id: 'contact-us',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 8,
          },
          11: {
            menuid: 287,
            url: '#',
            title: 'Group Visits',
            post_id: 'group-visits',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 9,
          },
          12: {
            menuid: 288,
            url: '#',
            title: 'Access & Inclusion',
            post_id: 'access-inclusion',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 10,
          },
          13: {
            menuid: 289,
            url: '#',
            title: 'FAQs',
            post_id: 'faqs',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 11,
          },
        },
      },
    },
    menuHeader: 'Visit Presidio',
    menuCard: {
      title: 'Event or Activity Card Example',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacini scelerisque',
      image: {
        ID: 362,
        id: 362,
        title: 'image 1',
        filename: 'image-1.png',
        filesize: 81746,
        url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/image-1.png',
        link: 'https://wpvip-presidio-gov.go-vip.net/?attachment_id=362',
        alt: '',
        author: '12',
        description: '',
        caption: '',
        name: 'image-1',
        status: 'inherit',
        uploaded_to: 276,
        date: '2023-03-13 10:03:31',
        modified: '2023-03-13 10:03:44',
        menu_order: 0,
        mime_type: 'image/png',
        type: 'image',
        subtype: 'png',
        icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
        width: 241,
        height: 144,
        sizes: [],
      },
      link: {
        title: 'Learn More',
        url: '#',
        target: '0',
      },
    },
  },
}

export const MegaMenuWithNoCard = Template.bind({})
MegaMenuWithNoCard.args = {
  menuData: {
    menuItems: {
      2: {
        menuid: 279,
        url: '#',
        title: 'Transit & Directions',
        post_id: 'transit-directions',
        menu_item_parent: '276',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 0,
        menuitem: {
          3: {
            menuid: 280,
            url: '#',
            title: 'Getting to & Around  the Park',
            post_id: 'getting-to-around-the-park',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 1,
          },
          4: {
            menuid: 281,
            url: '#',
            title: 'Presidio Go Shuttle',
            post_id: 'presidio-go-shuttle',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 2,
          },
          5: {
            menuid: 282,
            url: '#',
            title: 'Parking',
            post_id: 'parking',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 3,
          },
          6: {
            menuid: 283,
            url: '#',
            title: 'Bike Rentals',
            post_id: 'bike-rentals',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 4,
          },
          7: {
            menuid: 284,
            url: '#',
            title: 'Maps',
            post_id: 'maps',
            menu_item_parent: '279',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 5,
          },
        },
      },
      8: {
        menuid: 285,
        url: '#',
        title: 'Visitor Services',
        post_id: 'visitor-services',
        menu_item_parent: '276',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 6,
        menuitem: {
          9: {
            menuid: 286,
            url: '#',
            title: 'Visitor Center',
            post_id: 'visitor-center',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 7,
          },
          10: {
            menuid: 290,
            url: '#',
            title: 'Contact Us',
            post_id: 'contact-us',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 8,
          },
          11: {
            menuid: 287,
            url: '#',
            title: 'Group Visits',
            post_id: 'group-visits',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 9,
          },
          12: {
            menuid: 288,
            url: '#',
            title: 'Access & Inclusion',
            post_id: 'access-inclusion',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 10,
          },
          13: {
            menuid: 289,
            url: '#',
            title: 'FAQs',
            post_id: 'faqs',
            menu_item_parent: '285',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 11,
          },
        },
      },
    },
    menuHeader: 'Visit Presidio',
  },
}

export const MegaMenuWithMaxColumns = Template.bind({})
MegaMenuWithMaxColumns.args = {
  menuData: {
    menuItems: {
      56: {
        menuid: 331,
        url: '#',
        title: 'Vision & Stewardship',
        post_id: 'vision-stewardship',
        menu_item_parent: '294',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 0,
        menuitem: {
          57: {
            menuid: 332,
            url: '#',
            title: 'History & Park Making',
            post_id: 'history-park-making',
            menu_item_parent: '331',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 1,
          },
          58: {
            menuid: 334,
            url: '#',
            title: 'Forever Park Strategy',
            post_id: 'forever-park-strategy',
            menu_item_parent: '331',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 2,
          },
          59: {
            menuid: 335,
            url: '#',
            title: 'Community',
            post_id: 'community',
            menu_item_parent: '331',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 3,
          },
          60: {
            menuid: 336,
            url: '#',
            title: 'Planning & Projects',
            post_id: 'planning-projects',
            menu_item_parent: '331',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 4,
          },
          61: {
            menuid: 337,
            url: '#',
            title: 'Nature & Sustainability',
            post_id: 'nature-sustainability',
            menu_item_parent: '331',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 5,
          },
          62: {
            menuid: 338,
            url: '#',
            title: 'Land Acknowledgement',
            post_id: 'land-acknowledgement',
            menu_item_parent: '331',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 6,
          },
        },
      },
      63: {
        menuid: 339,
        url: '#',
        title: 'The Presidio Trust',
        post_id: 'the-presidio-trust',
        menu_item_parent: '294',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 7,
        menuitem: {
          64: {
            menuid: 340,
            url: '#',
            title: 'About the Presidio Trust',
            post_id: 'about-the-presidio-trust',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 8,
          },
          65: {
            menuid: 341,
            url: '#',
            title: 'Board & Executive Team',
            post_id: 'board-executive-team',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 9,
          },
          66: {
            menuid: 342,
            url: '#',
            title: 'Careers',
            post_id: 'careers',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 10,
          },
          67: {
            menuid: 343,
            url: '#',
            title: 'Partnership for the Presidio',
            post_id: 'partnership-for-the-presidio',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 11,
          },
          68: {
            menuid: 344,
            url: '#',
            title: 'Press Room',
            post_id: 'press-room',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 12,
          },
          69: {
            menuid: 345,
            url: '#',
            title: 'Research Resources',
            post_id: 'research-resources',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 13,
          },
          70: {
            menuid: 347,
            url: '#',
            title: 'Budget & Performance',
            post_id: 'budget-performance',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 14,
          },
          71: {
            menuid: 346,
            url: '#',
            title: 'Contact & Feedback',
            post_id: 'contact-feedback',
            menu_item_parent: '339',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 15,
          },
        },
      },
      72: {
        menuid: 348,
        url: '#',
        title: 'Permits',
        post_id: 'permits',
        menu_item_parent: '294',
        description: '',
        classes: ['parent'],
        type_label: 'Custom Link',
        seq_no: 16,
        menuitem: {
          73: {
            menuid: 349,
            url: '#',
            title: 'Park Use Permits',
            post_id: 'park-use-permits',
            menu_item_parent: '348',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 17,
          },
          74: {
            menuid: 350,
            url: '#',
            title: 'Outdoor Event FAQs',
            post_id: 'outdoor-event-faqs',
            menu_item_parent: '348',
            description: '',
            classes: [''],
            type_label: 'Custom Link',
            seq_no: 18,
          },
        },
      },
    },
    menuHeader: 'About Presidio',
    menuCard: {
      title: 'Presidio Slow Streets lorem ipsum dolor sit ',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lacinia scelerisque mauris eu facilisis.',
      image: {
        ID: 362,
        id: 362,
        title: 'image 1',
        filename: 'image-1.png',
        filesize: 81746,
        url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/image-1.png',
        link: 'https://wpvip-presidio-gov.go-vip.net/?attachment_id=362',
        alt: '',
        author: '12',
        description: '',
        caption: '',
        name: 'image-1',
        status: 'inherit',
        uploaded_to: 276,
        date: '2023-03-13 10:03:31',
        modified: '2023-03-13 10:03:44',
        menu_order: 0,
        mime_type: 'image/png',
        type: 'image',
        subtype: 'png',
        icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
        width: 241,
        height: 144,
        sizes: [],
      },
      link: {
        title: 'Learn More',
        url: '#',
        target: '0',
      },
    },
  },
}
