import React from 'react'
import Footer from 'src/components/footer/Footer'

export default {
  title: 'Footer',
  component: Footer,
}

const Template = (args) => <Footer {...args} />

export const FooterDefault = Template.bind({})
FooterDefault.args = {
  data: {
    footer: {
      logo: {
        title: 'presidio-logo (1)',
        filename: 'presidio-logo-1.webp',
        filesize: 3953,
        url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/presidio-logo-1.webp',
        link: 'https://wpvip-presidio-gov.go-vip.net/presidio-logo-1',
        alt: '',
        author: '12',
        description: '',
        caption: '',
        name: 'presidio-logo-1',
        status: 'inherit',
        uploaded_to: 0,
        date: '2023-03-07 10:10:26',
        modified: '2023-03-07 10:10:26',
        menu_order: 0,
        mime_type: 'image/webp',
        type: 'image',
        subtype: 'webp',
        icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
        width: 607,
        height: 134,
        sizes: [],
      },
      footer_menu: {
        name: 'Footer Menu',
        slug: 'footer-menu',
        count: 32,
        menu_items: {
          1: {
            menuid: 238,
            url: '#',
            title: 'Visit',
            post_id: 'visit-2',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 0,
            menuitem: {
              2: {
                menuid: 239,
                url: '#',
                title: 'Contact & Feedback',
                post_id: 'contact-feedback-2',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              3: {
                menuid: 240,
                url: '#',
                title: 'Maps',
                post_id: 'maps-2',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              4: {
                menuid: 241,
                url: '#',
                title: 'Visitor Center',
                post_id: 'visitor-center-2',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              5: {
                menuid: 242,
                url: '#',
                title: 'Getting Here',
                post_id: 'getting-here',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 3,
              },
            },
          },
          6: {
            menuid: 243,
            url: '#',
            title: 'Explore',
            post_id: 'explore-2',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 1,
            menuitem: {
              7: {
                menuid: 244,
                url: '#',
                title: 'Park Attractions',
                post_id: 'park-attractions',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              8: {
                menuid: 245,
                url: '#',
                title: 'Presidio Tunnel Tops',
                post_id: 'presidio-tunnel-tops',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              9: {
                menuid: 246,
                url: '#',
                title: 'Golf',
                post_id: 'golf',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              10: {
                menuid: 247,
                url: '#',
                title: 'Trails',
                post_id: 'trails',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 3,
              },
              11: {
                menuid: 248,
                url: '#',
                title: 'Education & Youth Programs',
                post_id: 'education-youth-programs',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 4,
              },
              12: {
                menuid: 249,
                url: '#',
                title: 'Blog',
                post_id: 'blog',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 5,
              },
            },
          },
          13: {
            menuid: 250,
            url: '#',
            title: 'Leasing',
            post_id: 'leasing',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 2,
            menuitem: {
              14: {
                menuid: 251,
                url: '#',
                title: 'Rent a Home',
                post_id: 'rent-a-home',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              15: {
                menuid: 252,
                url: '#',
                title: 'Resident Portal',
                post_id: 'resident-portal',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              16: {
                menuid: 253,
                url: '#',
                title: 'Commercial Leasing',
                post_id: 'commercial-leasing',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              17: {
                menuid: 254,
                url: '#',
                title: 'Commercial Tenant Portal',
                post_id: 'commercial-tenant-portal',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 3,
              },
            },
          },
          18: {
            menuid: 255,
            url: '#',
            title: 'Weddings & Events',
            post_id: 'weddings-events',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 3,
            menuitem: {
              19: {
                menuid: 256,
                url: '#',
                title: 'Event Venues for Rent',
                post_id: 'event-venues-for-rent',
                menu_item_parent: '255',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              20: {
                menuid: 257,
                url: '#',
                title: 'Party Venues',
                post_id: 'party-venues',
                menu_item_parent: '255',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              21: {
                menuid: 258,
                url: '#',
                title: 'Meetings & Conferences',
                post_id: 'meetings-conferences',
                menu_item_parent: '255',
                type_label: 'Custom Link',
                seq_no: 2,
              },
            },
          },
          22: {
            menuid: 259,
            url: '#',
            title: 'About the Presidio',
            post_id: 'about-the-presidio',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 4,
            menuitem: {
              23: {
                menuid: 260,
                url: '#',
                title: 'Park Use Permits',
                post_id: 'park-use-permits-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              24: {
                menuid: 261,
                url: '#',
                title: 'Research Resources',
                post_id: 'research-resources-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              25: {
                menuid: 262,
                url: '#',
                title: 'About the Presidio Trust',
                post_id: 'about-the-presidio-trust-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              26: {
                menuid: 263,
                url: '#',
                title: 'Press',
                post_id: 'press',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 3,
              },
              27: {
                menuid: 264,
                url: '#',
                title: 'Support a Presidio Business',
                post_id: 'support-a-presidio-business-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 4,
              },
            },
          },
          28: {
            menuid: 265,
            url: '#',
            title: 'Legal Links',
            post_id: 'legal-links',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 5,
            menuitem: {
              29: {
                menuid: 266,
                url: '#',
                title: 'Freedom of Information Act',
                post_id: 'freedom-of-information-act',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              30: {
                menuid: 267,
                url: '#',
                title: 'Accessibility Statement',
                post_id: 'accessibility-statement',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              31: {
                menuid: 268,
                url: '#',
                title: 'Links Disclaimer',
                post_id: 'links-disclaimer',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              32: {
                menuid: 269,
                url: '#',
                title: 'Waste, Fraud & Abuse Hotline',
                post_id: 'waste-fraud-abuse-hotline',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 3,
              },
            },
          },
        },
      },
      our_sponser_large: [
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO',
            filename: 'LOGO.png',
            filesize: 1650,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:23:33',
            modified: '2023-03-15 09:23:33',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 95,
            height: 30,
            sizes: [],
          },
        },
      ],
      our_sponser_small: [
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
        {
          logo: {
            title: 'LOGO_small',
            filename: 'LOGO_small.png',
            filesize: 1310,
            url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/LOGO_small.png',
            link: 'https://wpvip-presidio-gov.go-vip.net/logo_small',
            alt: '',
            author: '12',
            description: '',
            caption: '',
            name: 'logo_small',
            status: 'inherit',
            uploaded_to: 0,
            date: '2023-03-15 09:25:24',
            modified: '2023-03-15 09:25:24',
            menu_order: 0,
            mime_type: 'image/png',
            type: 'image',
            subtype: 'png',
            icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
            width: 76,
            height: 24,
            sizes: [],
          },
        },
      ],
      social_menu: {
        name: 'Social Menu',
        slug: 'social-menu',
        count: 4,
        menu_items: {
          0: {
            menuid: 270,
            url: '#',
            title: 'Facebook',
            post_id: 'facebook',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['facebook'],
          },
          1: {
            menuid: 273,
            url: '#',
            title: 'Youtube',
            post_id: 'youtube',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['youtube'],
          },
          2: {
            menuid: 271,
            url: '#',
            title: 'Twitter',
            post_id: 'twitter',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['twitter'],
          },
          3: {
            menuid: 272,
            url: '#',
            title: 'Instagram',
            post_id: 'instagram',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['instagram'],
          },
          menuid: '',
          url: '',
          title: '',
          post_id: '',
          menu_item_parent: '',
          type_label: '',
          classes: '',
        },
      },
      copy: 'Presidio Trust 2023',
      'privacy_&_policy': {
        title: 'Privacy Policy',
        url: '#',
        target: '0',
      },
      news_letter: {
        footer_news_title: 'Get Presidio News and Events',
        footer_news_description:
          'Sign up to receive the latest updates from the Presidio, and then come visit us!',
        footer_newsletter_thankyoutext: '',
        footer_newsletter_errortext: '',
        api: '',
      },
      usa_gov_text:
        'An official website of the United States Government  | Visit ',
      usa_gov_link: {
        title: 'USA.gov',
        url: '#',
        target: '0',
      },
    },
  },
}

export const FooterWithoutSponsors = Template.bind({})

FooterWithoutSponsors.args = {
  data: {
    footer: {
      logo: {
        title: 'presidio-logo (1)',
        filename: 'presidio-logo-1.webp',
        filesize: 3953,
        url: 'https://wpvip-presidio-gov.go-vip.net/wp-content/uploads/2023/03/presidio-logo-1.webp',
        link: 'https://wpvip-presidio-gov.go-vip.net/presidio-logo-1',
        alt: '',
        author: '12',
        description: '',
        caption: '',
        name: 'presidio-logo-1',
        status: 'inherit',
        uploaded_to: 0,
        date: '2023-03-07 10:10:26',
        modified: '2023-03-07 10:10:26',
        menu_order: 0,
        mime_type: 'image/webp',
        type: 'image',
        subtype: 'webp',
        icon: 'https://wpvip-presidio-gov.go-vip.net/wp-includes/images/media/default.png',
        width: 607,
        height: 134,
        sizes: [],
      },
      footer_menu: {
        name: 'Footer Menu',
        slug: 'footer-menu',
        count: 32,
        menu_items: {
          1: {
            menuid: 238,
            url: '#',
            title: 'Visit',
            post_id: 'visit-2',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 0,
            menuitem: {
              2: {
                menuid: 239,
                url: '#',
                title: 'Contact & Feedback',
                post_id: 'contact-feedback-2',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              3: {
                menuid: 240,
                url: '#',
                title: 'Maps',
                post_id: 'maps-2',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              4: {
                menuid: 241,
                url: '#',
                title: 'Visitor Center',
                post_id: 'visitor-center-2',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              5: {
                menuid: 242,
                url: '#',
                title: 'Getting Here',
                post_id: 'getting-here',
                menu_item_parent: '238',
                type_label: 'Custom Link',
                seq_no: 3,
              },
            },
          },
          6: {
            menuid: 243,
            url: '#',
            title: 'Explore',
            post_id: 'explore-2',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 1,
            menuitem: {
              7: {
                menuid: 244,
                url: '#',
                title: 'Park Attractions',
                post_id: 'park-attractions',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              8: {
                menuid: 245,
                url: '#',
                title: 'Presidio Tunnel Tops',
                post_id: 'presidio-tunnel-tops',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              9: {
                menuid: 246,
                url: '#',
                title: 'Golf',
                post_id: 'golf',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              10: {
                menuid: 247,
                url: '#',
                title: 'Trails',
                post_id: 'trails',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 3,
              },
              11: {
                menuid: 248,
                url: '#',
                title: 'Education & Youth Programs',
                post_id: 'education-youth-programs',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 4,
              },
              12: {
                menuid: 249,
                url: '#',
                title: 'Blog',
                post_id: 'blog',
                menu_item_parent: '243',
                type_label: 'Custom Link',
                seq_no: 5,
              },
            },
          },
          13: {
            menuid: 250,
            url: '#',
            title: 'Leasing',
            post_id: 'leasing',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 2,
            menuitem: {
              14: {
                menuid: 251,
                url: '#',
                title: 'Rent a Home',
                post_id: 'rent-a-home',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              15: {
                menuid: 252,
                url: '#',
                title: 'Resident Portal',
                post_id: 'resident-portal',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              16: {
                menuid: 253,
                url: '#',
                title: 'Commercial Leasing',
                post_id: 'commercial-leasing',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              17: {
                menuid: 254,
                url: '#',
                title: 'Commercial Tenant Portal',
                post_id: 'commercial-tenant-portal',
                menu_item_parent: '250',
                type_label: 'Custom Link',
                seq_no: 3,
              },
            },
          },
          18: {
            menuid: 255,
            url: '#',
            title: 'Weddings & Events',
            post_id: 'weddings-events',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 3,
            menuitem: {
              19: {
                menuid: 256,
                url: '#',
                title: 'Event Venues for Rent',
                post_id: 'event-venues-for-rent',
                menu_item_parent: '255',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              20: {
                menuid: 257,
                url: '#',
                title: 'Party Venues',
                post_id: 'party-venues',
                menu_item_parent: '255',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              21: {
                menuid: 258,
                url: '#',
                title: 'Meetings & Conferences',
                post_id: 'meetings-conferences',
                menu_item_parent: '255',
                type_label: 'Custom Link',
                seq_no: 2,
              },
            },
          },
          22: {
            menuid: 259,
            url: '#',
            title: 'About the Presidio',
            post_id: 'about-the-presidio',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 4,
            menuitem: {
              23: {
                menuid: 260,
                url: '#',
                title: 'Park Use Permits',
                post_id: 'park-use-permits-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              24: {
                menuid: 261,
                url: '#',
                title: 'Research Resources',
                post_id: 'research-resources-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              25: {
                menuid: 262,
                url: '#',
                title: 'About the Presidio Trust',
                post_id: 'about-the-presidio-trust-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              26: {
                menuid: 263,
                url: '#',
                title: 'Press',
                post_id: 'press',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 3,
              },
              27: {
                menuid: 264,
                url: '#',
                title: 'Support a Presidio Business',
                post_id: 'support-a-presidio-business-2',
                menu_item_parent: '259',
                type_label: 'Custom Link',
                seq_no: 4,
              },
            },
          },
          28: {
            menuid: 265,
            url: '#',
            title: 'Legal Links',
            post_id: 'legal-links',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            seq_no: 5,
            menuitem: {
              29: {
                menuid: 266,
                url: '#',
                title: 'Freedom of Information Act',
                post_id: 'freedom-of-information-act',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 0,
              },
              30: {
                menuid: 267,
                url: '#',
                title: 'Accessibility Statement',
                post_id: 'accessibility-statement',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 1,
              },
              31: {
                menuid: 268,
                url: '#',
                title: 'Links Disclaimer',
                post_id: 'links-disclaimer',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 2,
              },
              32: {
                menuid: 269,
                url: '#',
                title: 'Waste, Fraud & Abuse Hotline',
                post_id: 'waste-fraud-abuse-hotline',
                menu_item_parent: '265',
                type_label: 'Custom Link',
                seq_no: 3,
              },
            },
          },
        },
      },
      our_sponser_large: false,
      our_sponser_small: false,
      social_menu: {
        name: 'Social Menu',
        slug: 'social-menu',
        count: 4,
        menu_items: {
          0: {
            menuid: 270,
            url: '#',
            title: 'Facebook',
            post_id: 'facebook',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['facebook'],
          },
          1: {
            menuid: 273,
            url: '#',
            title: 'Youtube',
            post_id: 'youtube',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['youtube'],
          },
          2: {
            menuid: 271,
            url: '#',
            title: 'Twitter',
            post_id: 'twitter',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['twitter'],
          },
          3: {
            menuid: 272,
            url: '#',
            title: 'Instagram',
            post_id: 'instagram',
            menu_item_parent: '0',
            type_label: 'Custom Link',
            classes: ['instagram'],
          },
          menuid: '',
          url: '',
          title: '',
          post_id: '',
          menu_item_parent: '',
          type_label: '',
          classes: '',
        },
      },
      copy: 'Presidio Trust 2023',
      'privacy_&_policy': {
        title: 'Privacy Policy',
        url: '#',
        target: '0',
      },
      news_letter: {
        footer_news_title: 'Get Presidio News and Events',
        footer_news_description:
          'Sign up to receive the latest updates from the Presidio, and then come visit us!',
        footer_newsletter_thankyoutext: '',
        footer_newsletter_errortext: '',
        api: '',
      },
      usa_gov_text:
        'An official website of the United States Government  | Visit ',
      usa_gov_link: {
        title: 'USA.gov',
        url: '#',
        target: '0',
      },
    },
  },
}
